name: mhu_dart_sourcegen
version: 1.0.0
description: Dart source code generation utilities
repository: https://github.com/maprohu/mhu_dart_sourcegen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_style: ^2.3.2
  resource_portable:  ^3.0.2
  pubspec_parse: ^1.2.3
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
